steps:
  # Artifact Registryリポジトリを作成（存在しない場合）
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create timefold-repo \
          --repository-format=docker \
          --location=us-central1 \
          --description="TimefoldAI Docker Repository" || true
  
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/timefold-repo/timefold-app', '.']
  
  # Artifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/timefold-repo/timefold-app']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'timefold-app',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/timefold-repo/timefold-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'CLOUD_RUN_ENVIRONMENT=true'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/timefold-repo/timefold-app'

# ビルド設定
timeout: '1200s'  # 20分のタイムアウト（TimefoldAI用）
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # 高性能マシンでビルド高速化